FROM node:latest

WORKDIR /app

COPY . .

ARG NEXT_PUBLIC_BACKEND_BASE_URL
ENV NEXT_PUBLIC_BACKEND_BASE_URL=${NEXT_PUBLIC_BACKEND_BASE_URL}
ARG NEXT_PUBLIC_AUTH_BASE_URL
ENV NEXT_PUBLIC_AUTH_BASE_URL=${NEXT_PUBLIC_AUTH_BASE_URL}
ARG NEXT_PUBLIC_MINIO_BASE_URL
ENV NEXT_PUBLIC_MINIO_BASE_URL=${NEXT_PUBLIC_MINIO_BASE_URL}
ARG NEXT_PUBLIC_AI
ENV NEXT_PUBLIC_AI=${NEXT_PUBLIC_AI}
ARG GOOGLE_GENERATIVE_AI_API_KEY
ENV GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}

RUN npm install
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]