services:
    evolve_frontend:
        # image: ghcr.io/evolutionary-algorithms-on-click/evolve_frontend:main
        # Comment the above line and uncomment the following lines
        # to build the image from the Dockerfile locally.
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NEXT_PUBLIC_BACKEND_BASE_URL=${NEXT_PUBLIC_BACKEND_BASE_URL}
            - NEXT_PUBLIC_AUTH_BASE_URL=${NEXT_PUBLIC_AUTH_BASE_URL}
            - NEXT_PUBLIC_MINIO_BASE_URL=${NEXT_PUBLIC_MINIO_BASE_URL}
            - NEXT_PUBLIC_AI=${NEXT_PUBLIC_AI}
            - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
        ports:
            - "3000:3000"
